### PR TITLE
Added new option - startedSpec

### PR DESCRIPTION
**Pull request by Xotabu4**
Updated readme.md with new option
Added new option - startedSpec - will report test name that was started to console
Default - false

### CODE REVIEW

**Comment by Xotabu4** [comment]
@razvanz Please review
I met a problem in my tests - when inside tests i have some outputs - it hard to understand to which test output belongs. Example - 

```
blablablabla
blablablabla
blablablabla
blablablabla
blablablabla
	✓  toggle sound on or off (38 s)
blablablabla
blablablabla
blablablabla
blablablabla
blablablablablablablabla
blablablabla
blablablabla
blablablabla
blablablablablablablabla
blablablabla
blablablabla
blablablabla
blablablabla
	✓  see Reward animation (37 s)
blablablabla
blablablabla
blablablabla
blablablabla
blablablabla
```

My PL adds posibility to report test name right after it was started:

```
» test
	▻  test1
blablablabla
blablablabla
blablablabla
blablablabla
blablablabla
	✓  test1 (0.001 s)
	▻  test2
blablablabla
blablablabla
blablablabla
blablablabla
blablablabla
	✓  test2 (0.001 s)
	▻  test3
blablablabla
blablablabla
blablablabla
blablablabla
blablablabla
	✓  test3 (0 s)
```

Cool, isn't it?

**Comment by Xotabu4** [comment]
Example from console (OSX)
screen shot 2016-03-22 at 2 12 59 pm

**Comment by Irynn** [comment]
Yay, I was waiting for smth like that for ages! This would greatly improve the readability of default logs

**Comment by razvanz** [comment]
Thanks, it looks good. 

I only have 1 consideration: I would prefer the color / symbol option to be named `starting` (or just `spec`), rather that `test` in order to maintain Jasmine's terminology. (You also missed adding this options to README.)

I'm not a native English speaker, hence it's more of a question: Wouldn't `startingSpec` better denote the time of logging rather than `startedSpec` ? It seems more accurate to me.

**Comment by Xotabu4** [comment]
@razvanz 
Renamed accordingly, README.md also updated, and added color, symbol options to readme.

I am also not native English speaker :)

**Comment by razvanz** [comment]
Released `0.2.0` with the changes.

Thanks for contributing!

**Pull request merged**
